export const home=require('./api/home.routes')
export const login=require('./api/login.routes')
export const logout=require('./api/logout.routes')
export const register=require('./api/register.routes')
export const allusers=require('./api/user.routes')
